### create
POST /person/
Host: localhost:8080
Content-Type: application/json

{
    "name":"Test Testsson",
    "age": 42,
    "pets": [
        {
            "name": "Fido",
            "alive": true
        },{
            "name": "pussy",
            "alive": false
        }
    ]
}

### list
GET /person/?sort[age]=asc&preload[naming]=pussy
Host: localhost:8080
Accept: application/json

### update
PUT /person/1
Host: localhost:8080
Content-Type: application/json

{
  "id": 1,
    "name": "Test Testzon",
    "age": 43,
    "pets": [
      {
        "name": "Fidoh",
        "alive": true
      }
    ]
}

### delete
DELETE /person/1
Host: localhost:8080

### read
GET /person/1?preload[status]=true
Host: localhost:8080
Accept: application/json

### patch
PATCH /person/1?preload[naming]=pussy
Host: localhost:8080
Content-Type: application/json
Accept: application/json

{
    "age": 42
}

### Delete a pet
DELETE /pet/5
Host: localhost:8080
Content-Type: application/json
Accept: application/json

### fetch pets
GET /pet/
Host: localhost:8080