### create
POST /
Host: localhost:8080
Content-Type: application/json

{
    "name":"Test Testsson",
    "age": 42,
    "pets": [
        {
            "name": "Fido",
            "alive": true
        },{
            "name": "pussy",
            "alive": false
        }
    ]
}

### list
GET /?where[age]=42&pets[]
Host: localhost:8080
Accept: application/json

### update
PUT /1
Host: localhost:8080
Content-Type: application/json

{
  "id": 1,
    "name": "Test Testzon",
    "age": 43,
    "pets": [
      {
        "id": 1,
        "name": "Fido",
        "alive": false
      },
      {
        "id": 2,
        "name": "pussy",
        "alive": false
      },
      {
        "id": 5,
        "name": "Fidoh",
        "alive": true
      }
    ]
}
### delete
DELETE /1
Host: localhost:8080

### read
GET /1?pets[all]=false
Host: localhost:8080
Accept: application/json

### patch
PATCH /1?pets[all]
Host: localhost:8080
Content-Type: application/json
Accept: application/json

{
    "age": 42
}

### Delete a pet
DELETE /pet/5
Host: localhost:8080
Content-Type: application/json
Accept: application/json