### create
POST /persons/
Host: localhost:8080
Content-Type: application/json

{
    "name":"Test Testsson",
    "age": 42,
    "pets": [
        {
            "name": "Fido",
            "alive": true
        },{
            "name": "pussy",
            "alive": false
        }
    ]
}

### list persons
GET /persons/?sort[age]=asc&preload[naming]=pussy&where[full_name]=Test Testsson
Host: localhost:8080
Accept: application/json

### update
PUT /persons/1?version[cas]=2934376705174364337
Host: localhost:8080
Content-Type: application/json

{
  "id": 1,
  "name": "Test Testzon",
  "age": 43,
  "pets": [
    {
      "name": "Fidoh",
      "alive": true
    }
  ]
}

### delete
DELETE /persons/1?version[cas]=0
Host: localhost:8080

### read
GET /persons/1?preload[plain]=true
Host: localhost:8080
Accept: application/json

### patch
PATCH /persons/1?version[cas]=2905387365997318812
Host: localhost:8080
Content-Type: application/json
Accept: application/json

{
    "age": 43
}

### Delete a pet
DELETE /pets/2
Host: localhost:8080
Content-Type: application/json
Accept: application/json

### fetch pets
GET /pets/
Host: localhost:8080

### Person meta
GET /persons/_meta
Host: localhost:8080

### Service meta
GET /_discover
Host: localhost:8080